### ISSUE TITLE
Refatorar Análise de Tarefas

### ISSUE THREAD

**Issue by iurisevero** [Interacao-Humano-Computador/2019.2-OLX#19]
## Descrição
Refatorar a Análise de Tarefas a partir do feedback recebido em sala.

## Tasks
- [ ] Criar documento de Análise de Tarefas
- [ ] Criar Diagrama de tarefas de compra
- [ ] Criar Diagrama de tarefas de venda
- [ ] Criar Diagrama de tarefas de compra e venda

## Critérios de aceitação
- [ ] O documento deve possuir os 3 diagramas pedidos pelo professor

**Comment by iurisevero** [comment]
A partir dos documentos escritos pelo @manuengsf e do primeiro diagrama de tarefas, foi criado o seguinte diagrama:

![analise_de_tarefas](https://user-images.githubusercontent.com/42645264/67771559-43d9c000-fa37-11e9-9b25-0ce8e2559523.png)
