### ISSUE TITLE
Criar um novo planejamento da avaliação do protótipo de baixa fidelidade

### ISSUE THREAD

**Issue by iurisevero** [Interacao-Humano-Computador/2019.2-OLX#22]
## Tasks
- [ ] As tarefas propostas para a pessoa avaliada devem passar por todo sistema proposto na Análise de Tarefas e no Story Board
- [ ] A avaliação deve responder perguntas mais concretas sobre o modelo proposto
    * Formular perguntas para definir o nível de satisfação do avaliado
- [ ] Deve ser possível para o avaliado quantificar a satisfação de acordo com a interface avaliada
