### ISSUE TITLE
Verficar Análise de Tarefas

### ISSUE THREAD

**Issue by iurisevero** [Interacao-Humano-Computador/2019.2-OLX#23]
## Tasks
- [x] Verificar se a notação está de acordo com o padrão determinado para o modelo de Análise Hierárquica de Tarefas (AHT)
- [x] Listar problemas encontrados
- [x] Corrigir problemas e atualizar a documentação na [Wiki](https://github.com/Interacao-Humano-Computador/2019.2-OLX/wiki)

**Links que podem ajudar com a realização da tarefas:**
* [Análise de Tarefas. Análise Hierárquica de Tarefas](https://docplayer.com.br/13376795-Analise-de-tarefas-analise-hierarquica-de-tarefas.html)
* [AHT Análise Hierárquica da Tarefa](http://www.inf.ufsc.br/~edla.ramos/ine5624/aulas/AHT.ppt) (Download de arquivo .ppt)

**Comment by heylisten64** [comment]
https://www.draw.io/#W1a61851e4179e71a%2F1A61851E4179E71A!11679 documento de refatoração

**Comment by heylisten64** [comment]
![image](https://user-images.githubusercontent.com/43069991/68845914-f1410a80-06aa-11ea-9248-1363d00e0483.png)
