### ISSUE TITLE
Criar avaliação heurística dos relatos dos protótipos

### ISSUE THREAD

**Issue by iurisevero** [Interacao-Humano-Computador/2019.2-OLX#24]
## Tasks
- [x] Reestruturar resultados das avaliações dos protótipos a partir da [avaliação heurística disponibilizada pelo professor](https://aprender.ead.unb.br/pluginfile.php/706217/mod_resource/content/1/Artigo%20Av%20Heuri%CC%81stica%20ac1_55.pdf)
- [x] Criar um documento contento todos os feedbacks dispostos no formato proposto no documento citado
- [x] Criar uma nova página na [Wiki](https://github.com/Interacao-Humano-Computador/2019.2-OLX/wiki), com o nome de "Avaliação Heurísticas do Relatos das Avaliações dos Protótipos"
    
    * O documento deve possuir a tabela de versionamento
