### ISSUE TITLE
Criar um novo protótipo de baixa fidelidade a partir da heurísticas documentadas

### ISSUE THREAD

**Issue by iurisevero** [Interacao-Humano-Computador/2019.2-OLX#25]
## Tasks
- [x] Criar um protótipo sem cor e sem logo marcas
- [x] O protótipo não precisa necessariamente ser manual
- [x] Deve contemplar todo sistema proposto na Análise de tarefas e no Story Boardas Heurísticas documentadas

**Comment by juniopereirab** [comment]
Eu utilizei a logomarca do OLX, mais por questão de menu de acesso a página principal. 
O prototipo pode ser acessado em: https://marvelapp.com/4j6502i
